src/Entity/Nome.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NomeRepository")
 */
class Nome
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    public function getId(): ?int
    {
        return $this->id;
    }
}

src/Entity/Usuarios.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsuariosRepository")
 */
class Usuarios
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $tipo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nome;

    
    /**
     * @ORM\Column(type="string", length=14)
     */
    private $cpf;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $r_social;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $cnpj;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTipo(): ?bool
    {
        return $this->tipo;
    }

    public function setTipo(bool $tipo): self
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function getNome(): ?string
    {
        return $this->nome;
    }

    public function setNome(string $nome): self
    {
        $this->nome = $nome;

        return $this;
    }

    
    public function getCpf(): ?int
    {
        return $this->cpf;
    }

    public function setCpf(int $cpf): self
    {
        $this->cpf = $cpf;

        return $this;
    }

    public function getRSocial(): ?string
    {
        return $this->r_social;
    }

    public function setRSocial(string $r_social): self
    {
        $this->r_social = $r_social;

        return $this;
    }

    public function getCnpj(): ?int
    {
        return $this->cnpj;
    }

    public function setCnpj(int $cnpj): self
    {
        $this->cnpj = $cnpj;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
}

src/Form/UsuariosType.php
<?php

namespace App\Form;

use App\Entity\Usuarios;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UsuariosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tipo')
            ->add('nome')
            ->add('cpf')
            ->add('r_social')
            ->add('cnpj')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Usuarios::class,
        ]);
    }
}

src/Controller/UsuariosController.php
<?php

namespace App\Controller;

use App\Entity\Usuarios;
use App\Form\UsuariosType;
use App\Repository\UsuariosRepository;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/** 
 * @Route("/")
*/
class UsuariosController extends AbstractController
{
    /**
     * @Route("/", name="usuario_index", methods={"GET"})
    */
    public function index(UsuariosRepository $usuariosRepository, LoggerInterface $logger): Response
    {
        $usuarios =  $usuariosRepository->findAll();
        return $this->render('index.html.twig', [
            'usuarios' => $usuarios,
        ]);
    }

    /**
     * @Route("/selecao", name="selecao")
    */
    public function selecao()
    {
        return $this->render('selecao.html.twig');
    }

    /**
     * @Route("/pfisica", name="new-pfisica")
    */
    public function pfisica(){
        return $this->render('pfisica.html.twig');
    }

    /**
     * @Route("/pjuridica", name="new-pjuridica")
    */
    public function pjuridica(){
        return $this->render('pjuridica.html.twig');
    }

    /**
     * @Route("/savepf", name="save_pf")
    */
    public function savepf(Request $request){
        $novo_cadastro = $request->request->all();

        $cadastro = new Usuarios();
        $cadastro->setNome($novo_cadastro['nome']);
        $cadastro->setCpf($novo_cadastro['cpf']);
        $cadastro->setEmail($novo_cadastro['email']);

        $doctrine = $this->getDoctrine()->getManager();
        $doctrine->persist($cadastro);
        $doctrine->flush();

        return $this->redirectToRoute('usuario_index');
    }

    /**
     * @Route("/savepj", name="save_pj")
    */
    public function savepj(Request $request){
        $novo_cadastro = $request->request->all();

        $cadastro = new Usuarios();
        $cadastro->setRSocial($novo_cadastro['r_social']);
        $cadastro->setCnpj($novo_cadastro['cnpj']);
        $cadastro->setEmail($novo_cadastro['email']);

        $doctrine = $this->getDoctrine()->getManager();
        $doctrine->persist($cadastro);
        $doctrine->flush();

        return $this->redirectToRoute('usuario_index');
    }

   
    /**
     * @Route("/{id}", name="show", methods={"GET"})
     */
    public function show(Usuarios $usuario): Response
    {
        return $this->render('show.html.twig', [
            'usuario' => $usuario,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Usuarios $usuario): Response
    {
        $form = $this->createForm(UsuariosType::class, $usuario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('usuario_index');
        }

        return $this->render('edit.html.twig', [
            'usuario' => $usuario,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="delete", methods={"DELETE"})
     */
    public function delete(Request $request, Usuarios $usuario): Response
    {
        if ($this->isCsrfTokenValid('delete'.$usuario->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($usuario);
            $entityManager->flush();
        }

        return $this->redirectToRoute('usuario_index');
    }
}

templates/_delete_form.html.twig
<form method="post" action="{{ path('delete', {'id': usuario.id}) }}" onsubmit="return confirm('Deseja excluir o registro?');">
    <input type="hidden" name="_method" value="DELETE" >
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ usuario.id) }}">
    <br>
    <button class="btn btn-danger">Delete</button>
</form>

templates/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/base.html.twig
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}        {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block stylesheets %}        {% endblock %}
  </head>
  <body  class="container">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block body %}{% endblock %}        {% block javascripts %}{% endblock %}
  </body>
</html>

templates/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar{% endblock %}

{% block body %}
    <h1>Editar Registro</h1>

    {{ include('_form.html.twig', {'button_label': 'Salvar'}) }}
    
    <a href="{{ path('usuario_index') }}" class="btn btn-warning">Voltar</a>

    {{ include('_delete_form.html.twig') }}
{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Registros{% endblock %}

{% block body %}
    <p class="display-4">Registros</p>
    <br>
    <div>
        <p><h5>Pessoa Fisica</h5></p>
        <table class="table">
            <thead>
                <tr>
                    <th width="300px">Nome</th>
                    <th width="300px">CPF</th>
                    <th width="300px">Email</th>
                    <th>Opções</th>
                </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}
                    <tr>
                        <td>{{ usuario.nome }}</td>
                        <td>{{ usuario.cpf }}</td>
                        <td>{{ usuario.email }}</td>
                        <td>
                            <a href="{{ path('show', {'id': usuario.id}) }}">Ver</a> | 
                            <a href="{{ path('edit', {'id': usuario.id}) }}">Editar</a>
                        </td>
                    </tr>
                    {% else %}
                        <tr>
                            <td colspan="8">Sem registros!</td>
                        </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <br>
    <hr/>
    <br>
    <div>
        <p><h5>Pessoa Juridica</h5></p>
        <table class="table">
            <thead>
                <tr>
                    <th width="300px">Razão Social</th>
                    <th width="300px">CNPJ</th>
                    <th width="300px">Email</th>
                    <th>Opções</th>
                </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}
                    <tr>
                        <td>{{ usuario.rSocial }}</td>
                        <td>{{ usuario.cnpj }}</td>
                        <td>{{ usuario.email }}</td>
                        <td>
                            <a href="{{ path('show', {'id': usuario.id}) }}">Ver</a> | 
                            <a href="{{ path('edit', {'id': usuario.id}) }}">Editar</a>
                        </td>
                    </tr>
                    {% else %}
                        <tr>
                            <td colspan="8">Sem registros!</td>
                        </tr>
                    {% endfor %}
            </tbody>
        </table>
     </div>

<a href="{{ path('selecao') }}" class="btn btn-primary">Novo Registro</a>
<br><br><br><br>
{% endblock %}

templates/pfisica.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Cadastro Pessoa Fisica
{% endblock %}
    
{% block body %}

<div class="display-4">Novo Cadastro Pessoa Fisica</div> <br>
    <form action="{{ path('save_pf') }}" method="POST" class="form-group">
        <p>
            <label for="nome">Nome: </label><br>
            <input type="text" name="nome" class="form-control">
        </p>

        <p>
            <label for="cpf">CPF</label><br>
            <input type="number" name="cpf" maxlength="11" class="form-control">
        </p>

        <p>
            <label for="email">Email</label><br>
            <input type="text" name="email" class="form-control">
        </p>

        <input type="submit" value="Cadastrar" class="btn btn-success">
    </form>

{% endblock %}

templates/pjuridica.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Cadastro Pessoa Juridica
{% endblock %}
    
{% block body %}

<div class="display-4">Novo Cadastro Pessoa Juridica</div> <br>

    <form action="{{ path('save_pj') }}" method="POST" class="form-group">
        <p>
            <label for="r_social">Razão Social: </label><br>
            <input type="text" name="r_social" class="form-control">
        </p>

        <p>
            <label for="cnpj">CNPJ</label><br>
            <input type="number" name="cnpj" maxlength="14" class="form-control">
        </p>

        <p>
            <label for="email">Email</label><br>
            <input type="text" name="email" class="form-control">
        </p>

        <input type="submit" value="Cadastrar" class="btn btn-success">
    </form>

{% endblock %}

templates/selecao.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cadastro{% endblock %}

{% block body %}
    <h3 class="display-4">Selecione a Opção de Cadastro</h3> <br>
    <form action="">
        <p>
            <select name="selecao" onchange="location = this.value" class="custom-select">
                <option value="">Selecione a Opção</option>
                <option value="{{ path('new-pfisica') }}">Pessoa Fisica</option>
                <option value="{{ path('new-pjuridica') }}">Pessoa Juridica</option>
            </select>
        </p>
    </form>


{% endblock %}

templates/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Registro{% endblock %}

{% block body %}
    <h1>Registro</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nome</th>
                <td>{{ usuario.nome }}</td>
            </tr>
            <tr>
                <th>CPF</th>
                <td>{{ usuario.cpf }}</td>
            </tr>
            <tr>
                <th>Razão social</th>
                <td>{{ usuario.rSocial }}</td>
            </tr>
            <tr>
                <th>CNPJ</th>
                <td>{{ usuario.cnpj }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ usuario.email }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('usuario_index') }}" class="btn btn-warning">Voltar</a>

    <a href="{{ path('edit', {'id': usuario.id}) }}" class="btn btn-primary">Editar</a>
    {{ include('_delete_form.html.twig') }}
{% endblock %}